### ISSUE TITLE
using the forward and back buttons multiple times during the application should not delete the data - need persistance

### ISSUE THREAD

**Issue by amitej** [atlantadoulaconnect/adc-app#106]

**Comment by mayaviust** [comment]
Controlling what happens when the back button is pressed on the app bar:
- https://medium.com/@iamatul_k/flutter-handle-back-button-in-a-flutter-application-override-back-arrow-button-in-app-bar-d17e0a3d41f

When back button is pressed while the user is filling out the application, the same actions as the "PREVIOUS" button are taken
